/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LobbyControllerFindAllParams,
  LobbyCreateDTO,
  LobbyResponseDto,
  LobbyUpdateDTO
} from '.././model';





export const lobbyControllerCreate = (
    lobbyCreateDTO: LobbyCreateDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LobbyResponseDto>> => {
    
    
    return axios.post(
      `http://localhost:3001/lobby`,
      lobbyCreateDTO,options
    );
  }



export const getLobbyControllerCreateMutationOptions = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerCreate>>, TError,{data: LobbyCreateDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerCreate>>, TError,{data: LobbyCreateDTO}, TContext> => {

const mutationKey = ['lobbyControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lobbyControllerCreate>>, {data: LobbyCreateDTO}> = (props) => {
          const {data} = props ?? {};

          return  lobbyControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LobbyControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof lobbyControllerCreate>>>
    export type LobbyControllerCreateMutationBody = LobbyCreateDTO
    export type LobbyControllerCreateMutationError = AxiosError<null | null>

    export const useLobbyControllerCreate = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerCreate>>, TError,{data: LobbyCreateDTO}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lobbyControllerCreate>>,
        TError,
        {data: LobbyCreateDTO},
        TContext
      > => {

      const mutationOptions = getLobbyControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Retrieves a paginated list of lobbies with optional filters for status, match type, and ranked.
 */
export const lobbyControllerFindAll = (
    params?: LobbyControllerFindAllParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LobbyResponseDto[]>> => {
    
    
    return axios.get(
      `http://localhost:3001/lobby`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getLobbyControllerFindAllQueryKey = (params?: LobbyControllerFindAllParams,) => {
    return [`http://localhost:3001/lobby`, ...(params ? [params]: [])] as const;
    }

    
export const getLobbyControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof lobbyControllerFindAll>>, TError = AxiosError<unknown>>(params?: LobbyControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbyControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLobbyControllerFindAllQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof lobbyControllerFindAll>>> = ({ signal }) => lobbyControllerFindAll(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof lobbyControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LobbyControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof lobbyControllerFindAll>>>
export type LobbyControllerFindAllQueryError = AxiosError<unknown>


export function useLobbyControllerFindAll<TData = Awaited<ReturnType<typeof lobbyControllerFindAll>>, TError = AxiosError<unknown>>(
 params: undefined |  LobbyControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbyControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof lobbyControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof lobbyControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLobbyControllerFindAll<TData = Awaited<ReturnType<typeof lobbyControllerFindAll>>, TError = AxiosError<unknown>>(
 params?: LobbyControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbyControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof lobbyControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof lobbyControllerFindAll>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLobbyControllerFindAll<TData = Awaited<ReturnType<typeof lobbyControllerFindAll>>, TError = AxiosError<unknown>>(
 params?: LobbyControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbyControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLobbyControllerFindAll<TData = Awaited<ReturnType<typeof lobbyControllerFindAll>>, TError = AxiosError<unknown>>(
 params?: LobbyControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbyControllerFindAll>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLobbyControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Retrieves detailed information about a specific lobby including owner and all players.
 */
export const lobbyControllerFindOne = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LobbyResponseDto>> => {
    
    
    return axios.get(
      `http://localhost:3001/lobby/${id}`,options
    );
  }


export const getLobbyControllerFindOneQueryKey = (id?: number,) => {
    return [`http://localhost:3001/lobby/${id}`] as const;
    }

    
export const getLobbyControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof lobbyControllerFindOne>>, TError = AxiosError<null>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbyControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLobbyControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof lobbyControllerFindOne>>> = ({ signal }) => lobbyControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof lobbyControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LobbyControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof lobbyControllerFindOne>>>
export type LobbyControllerFindOneQueryError = AxiosError<null>


export function useLobbyControllerFindOne<TData = Awaited<ReturnType<typeof lobbyControllerFindOne>>, TError = AxiosError<null>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbyControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof lobbyControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof lobbyControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLobbyControllerFindOne<TData = Awaited<ReturnType<typeof lobbyControllerFindOne>>, TError = AxiosError<null>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbyControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof lobbyControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof lobbyControllerFindOne>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLobbyControllerFindOne<TData = Awaited<ReturnType<typeof lobbyControllerFindOne>>, TError = AxiosError<null>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbyControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLobbyControllerFindOne<TData = Awaited<ReturnType<typeof lobbyControllerFindOne>>, TError = AxiosError<null>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbyControllerFindOne>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLobbyControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Updates lobby settings. Owner only. Cannot update after match starts.
 */
export const lobbyControllerUpdate = (
    id: number,
    lobbyUpdateDTO: LobbyUpdateDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LobbyResponseDto>> => {
    
    
    return axios.patch(
      `http://localhost:3001/lobby/${id}`,
      lobbyUpdateDTO,options
    );
  }



export const getLobbyControllerUpdateMutationOptions = <TError = AxiosError<null | null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerUpdate>>, TError,{id: number;data: LobbyUpdateDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerUpdate>>, TError,{id: number;data: LobbyUpdateDTO}, TContext> => {

const mutationKey = ['lobbyControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lobbyControllerUpdate>>, {id: number;data: LobbyUpdateDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  lobbyControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LobbyControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof lobbyControllerUpdate>>>
    export type LobbyControllerUpdateMutationBody = LobbyUpdateDTO
    export type LobbyControllerUpdateMutationError = AxiosError<null | null | null>

    export const useLobbyControllerUpdate = <TError = AxiosError<null | null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerUpdate>>, TError,{id: number;data: LobbyUpdateDTO}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lobbyControllerUpdate>>,
        TError,
        {id: number;data: LobbyUpdateDTO},
        TContext
      > => {

      const mutationOptions = getLobbyControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const lobbyControllerDelete = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<null>> => {
    
    
    return axios.delete(
      `http://localhost:3001/lobby/${id}`,options
    );
  }



export const getLobbyControllerDeleteMutationOptions = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerDelete>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerDelete>>, TError,{id: number}, TContext> => {

const mutationKey = ['lobbyControllerDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lobbyControllerDelete>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  lobbyControllerDelete(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LobbyControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof lobbyControllerDelete>>>
    
    export type LobbyControllerDeleteMutationError = AxiosError<null | null>

    export const useLobbyControllerDelete = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerDelete>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lobbyControllerDelete>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getLobbyControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const lobbyControllerJoin = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<null>> => {
    
    
    return axios.post(
      `http://localhost:3001/lobby/${id}/join`,undefined,options
    );
  }



export const getLobbyControllerJoinMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerJoin>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerJoin>>, TError,{id: string}, TContext> => {

const mutationKey = ['lobbyControllerJoin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lobbyControllerJoin>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  lobbyControllerJoin(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LobbyControllerJoinMutationResult = NonNullable<Awaited<ReturnType<typeof lobbyControllerJoin>>>
    
    export type LobbyControllerJoinMutationError = AxiosError<unknown>

    export const useLobbyControllerJoin = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerJoin>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lobbyControllerJoin>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getLobbyControllerJoinMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const lobbyControllerLeave = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<null>> => {
    
    
    return axios.post(
      `http://localhost:3001/lobby/${id}/leave`,undefined,options
    );
  }



export const getLobbyControllerLeaveMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerLeave>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerLeave>>, TError,{id: string}, TContext> => {

const mutationKey = ['lobbyControllerLeave'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lobbyControllerLeave>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  lobbyControllerLeave(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LobbyControllerLeaveMutationResult = NonNullable<Awaited<ReturnType<typeof lobbyControllerLeave>>>
    
    export type LobbyControllerLeaveMutationError = AxiosError<unknown>

    export const useLobbyControllerLeave = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerLeave>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lobbyControllerLeave>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getLobbyControllerLeaveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Toggles the ready status of the player in the lobby. Cannot be changed after match starts.
 */
export const lobbyControllerReady = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<null>> => {
    
    
    return axios.post(
      `http://localhost:3001/lobby/${id}/ready`,undefined,options
    );
  }



export const getLobbyControllerReadyMutationOptions = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerReady>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerReady>>, TError,{id: number}, TContext> => {

const mutationKey = ['lobbyControllerReady'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lobbyControllerReady>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  lobbyControllerReady(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LobbyControllerReadyMutationResult = NonNullable<Awaited<ReturnType<typeof lobbyControllerReady>>>
    
    export type LobbyControllerReadyMutationError = AxiosError<null | null>

    export const useLobbyControllerReady = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerReady>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lobbyControllerReady>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getLobbyControllerReadyMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Starts the match. Owner only. Requires 10 players, all ready, and past scheduled time.
 */
export const lobbyControllerStart = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LobbyResponseDto>> => {
    
    
    return axios.post(
      `http://localhost:3001/lobby/${id}/start`,undefined,options
    );
  }



export const getLobbyControllerStartMutationOptions = <TError = AxiosError<null | null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerStart>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerStart>>, TError,{id: number}, TContext> => {

const mutationKey = ['lobbyControllerStart'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lobbyControllerStart>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  lobbyControllerStart(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LobbyControllerStartMutationResult = NonNullable<Awaited<ReturnType<typeof lobbyControllerStart>>>
    
    export type LobbyControllerStartMutationError = AxiosError<null | null | null>

    export const useLobbyControllerStart = <TError = AxiosError<null | null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyControllerStart>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lobbyControllerStart>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getLobbyControllerStartMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    