/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LobbySseControllerStreamParams
} from '.././model';





/**
 * Establish Server-Sent Events connection for real-time lobby updates
 */
export const lobbySseControllerStream = (
    params?: LobbySseControllerStreamParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<null>> => {
    
    
    return axios.get(
      `http://localhost:3001/lobby/sse/stream`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getLobbySseControllerStreamQueryKey = (params?: LobbySseControllerStreamParams,) => {
    return [`http://localhost:3001/lobby/sse/stream`, ...(params ? [params]: [])] as const;
    }

    
export const getLobbySseControllerStreamQueryOptions = <TData = Awaited<ReturnType<typeof lobbySseControllerStream>>, TError = AxiosError<unknown>>(params?: LobbySseControllerStreamParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbySseControllerStream>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLobbySseControllerStreamQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof lobbySseControllerStream>>> = ({ signal }) => lobbySseControllerStream(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof lobbySseControllerStream>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LobbySseControllerStreamQueryResult = NonNullable<Awaited<ReturnType<typeof lobbySseControllerStream>>>
export type LobbySseControllerStreamQueryError = AxiosError<unknown>


export function useLobbySseControllerStream<TData = Awaited<ReturnType<typeof lobbySseControllerStream>>, TError = AxiosError<unknown>>(
 params: undefined |  LobbySseControllerStreamParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbySseControllerStream>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof lobbySseControllerStream>>,
          TError,
          Awaited<ReturnType<typeof lobbySseControllerStream>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLobbySseControllerStream<TData = Awaited<ReturnType<typeof lobbySseControllerStream>>, TError = AxiosError<unknown>>(
 params?: LobbySseControllerStreamParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbySseControllerStream>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof lobbySseControllerStream>>,
          TError,
          Awaited<ReturnType<typeof lobbySseControllerStream>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLobbySseControllerStream<TData = Awaited<ReturnType<typeof lobbySseControllerStream>>, TError = AxiosError<unknown>>(
 params?: LobbySseControllerStreamParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbySseControllerStream>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLobbySseControllerStream<TData = Awaited<ReturnType<typeof lobbySseControllerStream>>, TError = AxiosError<unknown>>(
 params?: LobbySseControllerStreamParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof lobbySseControllerStream>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLobbySseControllerStreamQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



