/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

export interface AuthCredentialsDto {
  /** User email address */
  email: string;
  /** User password */
  password: string;
}
