/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { CreatePlayerDtoPrimaryRole } from './createPlayerDtoPrimaryRole';
import type { CreatePlayerDtoSecondaryRole } from './createPlayerDtoSecondaryRole';

export interface CreatePlayerDto {
  /** Riot Games Player GameName */
  gameName: string;
  /** Riot Games Player TagLine */
  tagLine: string;
  /** primary role declared by player */
  primaryRole: CreatePlayerDtoPrimaryRole;
  /** primary role declared by player */
  secondaryRole: CreatePlayerDtoSecondaryRole;
  /** description for users profile */
  description: string;
}
