/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * primary role declared by player
 */
export type CreatePlayerDtoPrimaryRole = typeof CreatePlayerDtoPrimaryRole[keyof typeof CreatePlayerDtoPrimaryRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePlayerDtoPrimaryRole = {
  TOP: 'TOP',
  JUNGLE: 'JUNGLE',
  MID: 'MID',
  CARRY: 'CARRY',
  SUPPORT: 'SUPPORT',
} as const;
