/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

export interface LobbyUpdateDTO {
  /** The title of the lobby */
  title?: string;
  /** The description of the lobby */
  description?: string;
  /** Indicates if the match is ranked */
  ranked?: boolean;
  /** The date and time of the match */
  date?: string;
}
