/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

export type LobbyControllerFindAllStatus = typeof LobbyControllerFindAllStatus[keyof typeof LobbyControllerFindAllStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LobbyControllerFindAllStatus = {
  SCHEDULED: 'SCHEDULED',
  STARTING: 'STARTING',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
} as const;
