/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Current status of the lobby
 */
export type LobbyResponseDtoStatus = typeof LobbyResponseDtoStatus[keyof typeof LobbyResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LobbyResponseDtoStatus = {
  SCHEDULED: 'SCHEDULED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
} as const;
