/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { LobbyResponseDtoStatus } from './lobbyResponseDtoStatus';
import type { LobbyResponseDtoMatchType } from './lobbyResponseDtoMatchType';
import type { LobbyResponseDtoOwner } from './lobbyResponseDtoOwner';
import type { LobbyPlayerResponseDto } from './lobbyPlayerResponseDto';

export interface LobbyResponseDto {
  /** Unique identifier of the lobby */
  id: number;
  /** The title of the lobby */
  title: string;
  /** The description of the lobby */
  description: string;
  /** Indicates if the match is ranked */
  ranked: boolean;
  /** Current status of the lobby */
  status: LobbyResponseDtoStatus;
  /** The type of the match */
  matchType: LobbyResponseDtoMatchType;
  /** The date and time of the match */
  date: string;
  /** Timestamp when the lobby was created */
  createdAt: string;
  /** Timestamp when the lobby was last updated */
  updatedAt: string;
  /**
   * ID of the player who owns the lobby
   * @nullable
   */
  ownerId: number | null;
  /**
   * Owner player account details
   * @nullable
   */
  owner: LobbyResponseDtoOwner;
  /** Players in the lobby */
  players: LobbyPlayerResponseDto[];
}
