/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

export type LobbySseControllerStreamParams = {
/**
 * Optional lobby ID to subscribe to specific lobby updates
 */
lobbyId?: number;
};
