/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * The type of the match
 */
export type LobbyCreateDTOMatchType = typeof LobbyCreateDTOMatchType[keyof typeof LobbyCreateDTOMatchType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LobbyCreateDTOMatchType = {
  Queue: 'Queue',
  Team: 'Team',
} as const;
