/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { LobbyPlayerResponseDtoPlayer } from './lobbyPlayerResponseDtoPlayer';

export interface LobbyPlayerResponseDto {
  /** Unique identifier for the lobby player record */
  id: number;
  /** ID of the lobby */
  lobbyId: number;
  /**
   * ID of the player account
   * @nullable
   */
  playerId: number | null;
  /** Team number (1 or 2) */
  team: number;
  /** Whether the player is ready */
  ready: boolean;
  /** Timestamp when player joined the lobby */
  joinedAt: string;
  /**
   * Player account details
   * @nullable
   */
  player: LobbyPlayerResponseDtoPlayer;
}
