/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { LobbyFiltersStatus } from './lobbyFiltersStatus';
import type { LobbyFiltersMatchType } from './lobbyFiltersMatchType';

export interface LobbyFilters {
  /** Filter lobbies by status */
  status?: LobbyFiltersStatus;
  /** Filter lobbies by match type */
  matchType?: LobbyFiltersMatchType;
  /** Filter lobbies by ranked status */
  ranked?: boolean;
  /** Filter lobbies with date greater than or equal to this date */
  dateFrom?: string;
  /** Filter lobbies with date less than or equal to this date */
  dateTo?: string;
}
