/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { LobbyControllerFindAllSortOrder } from './lobbyControllerFindAllSortOrder';
import type { LobbyControllerFindAllStatus } from './lobbyControllerFindAllStatus';
import type { LobbyControllerFindAllMatchType } from './lobbyControllerFindAllMatchType';

export type LobbyControllerFindAllParams = {
/**
 * Page number (starts from 1)
 */
page?: number;
/**
 * Number of items per page
 */
limit?: number;
/**
 * Offset for pagination
 */
offset?: number;
/**
 * Search term for filtering results
 */
search?: string;
/**
 * Field to sort by
 */
sortBy?: string;
/**
 * Sort order
 */
sortOrder?: LobbyControllerFindAllSortOrder;
/**
 * Filter lobbies by status
 */
status?: LobbyControllerFindAllStatus;
/**
 * Filter lobbies by match type
 */
matchType?: LobbyControllerFindAllMatchType;
/**
 * Filter lobbies by ranked status
 */
ranked?: boolean;
/**
 * Filter lobbies with date greater than or equal to this date
 */
dateFrom?: string;
/**
 * Filter lobbies with date less than or equal to this date
 */
dateTo?: string;
};
