/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { PlayerResponseDto } from './playerResponseDto';

/**
 * Owner player account details
 * @nullable
 */
export type LobbyResponseDtoOwner = PlayerResponseDto | null;
