/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

export type LobbyControllerFindAllMatchType = typeof LobbyControllerFindAllMatchType[keyof typeof LobbyControllerFindAllMatchType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LobbyControllerFindAllMatchType = {
  Queue: 'Queue',
  Team: 'Team',
} as const;
