/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Player role in the match
 */
export type MatchParticipantResponseDtoRole = typeof MatchParticipantResponseDtoRole[keyof typeof MatchParticipantResponseDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MatchParticipantResponseDtoRole = {
  TOP: 'TOP',
  JUNGLE: 'JUNGLE',
  MID: 'MID',
  CARRY: 'CARRY',
  SUPPORT: 'SUPPORT',
} as const;
