/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { MatchParticipantResponseDto } from './matchParticipantResponseDto';

export interface MatchResponseDto {
  /** Match ID */
  id: number;
  /** Lobby ID */
  lobbyId: number;
  /** Riot match ID */
  riotMatchId: string;
  /**
   * Match duration in seconds (null if ongoing)
   * @nullable
   */
  duration?: number | null;
  /**
   * Winning team ID (100 or 200, null if ongoing)
   * @nullable
   */
  winningTeam?: number | null;
  /** Match creation timestamp */
  createdAt: string;
  /** Match last update timestamp */
  updatedAt: string;
  /** List of match participants */
  participants: MatchParticipantResponseDto[];
}
