/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { OrganizationResponseDtoOwner } from './organizationResponseDtoOwner';

export interface OrganizationResponseDto {
  /** Organization ID */
  id: number;
  /** Organization name */
  name: string;
  /** Owner user ID */
  ownerId: number;
  /** Organization owner */
  owner: OrganizationResponseDtoOwner;
}
