/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

export type PlayerControllerPlayersSortOrder = typeof PlayerControllerPlayersSortOrder[keyof typeof PlayerControllerPlayersSortOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlayerControllerPlayersSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
