/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

export interface PlayerPostingCreateDto {
  /** Title of the player posting */
  title: string;
  /** Detailed description of the posting */
  description?: string;
}
