/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { PlayerResponseDtoPrimaryRole } from './playerResponseDtoPrimaryRole';
import type { PlayerResponseDtoSecondaryRole } from './playerResponseDtoSecondaryRole';

export interface PlayerResponseDto {
  /** Unique identifier for the player account */
  id: number;
  /** Unique identifier for the user account */
  userId: number;
  /** description for users profile */
  description: string;
  /** rating for a player */
  rating: number;
  /**
   * Riot Games Player GameName
   * @nullable
   */
  gameName: string | null;
  /**
   * Riot Games Player TagLine
   * @nullable
   */
  tagLine: string | null;
  /**
   * primary role declared by player
   * @nullable
   */
  primaryRole: PlayerResponseDtoPrimaryRole;
  /**
   * primary role declared by player
   * @nullable
   */
  secondaryRole: PlayerResponseDtoSecondaryRole;
  /**
   * Player unique identifier from Riot API
   * @nullable
   */
  puuid: string | null;
  /**
   * Profile icon ID of the player
   * @nullable
   */
  profileIconId: number | null;
  /**
   * Summoner level of the player
   * @nullable
   */
  summonerLevel: number | null;
}
