/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { PlayerPostingResponseDtoStatus } from './playerPostingResponseDtoStatus';
import type { PlayerResponseDto } from './playerResponseDto';

export interface PlayerPostingResponseDto {
  /** Title of the player posting */
  title: string;
  /** Detailed description of the posting */
  description?: string;
  /** Unique identifier for the posting */
  id: number;
  /** ID of the player that created the posting */
  playerId: number;
  /** Current status of the posting */
  status: PlayerPostingResponseDtoStatus;
  /** When the posting was created */
  createdAt: string;
  /** When the posting was last updated */
  updatedAt: string;
  /** The player that created the posting */
  player: PlayerResponseDto;
}
