/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { PlayerResponseDtoGameName } from './playerResponseDtoGameName';
import type { PlayerResponseDtoTagLine } from './playerResponseDtoTagLine';
import type { PlayerResponseDtoPrimaryRole } from './playerResponseDtoPrimaryRole';
import type { PlayerResponseDtoSecondaryRole } from './playerResponseDtoSecondaryRole';
import type { PlayerResponseDtoPuuid } from './playerResponseDtoPuuid';
import type { PlayerResponseDtoProfileIconId } from './playerResponseDtoProfileIconId';
import type { PlayerResponseDtoSummonerLevel } from './playerResponseDtoSummonerLevel';

export interface PlayerResponseDto {
  /** Unique identifier for the player account */
  id: number;
  /** Unique identifier for the user account */
  userId: number;
  /** description for users profile */
  description: string;
  /** rating for a player */
  rating: number;
  /** Riot Games Player GameName */
  gameName: PlayerResponseDtoGameName;
  /** Riot Games Player TagLine */
  tagLine: PlayerResponseDtoTagLine;
  /** primary role declared by player */
  primaryRole: PlayerResponseDtoPrimaryRole;
  /** primary role declared by player */
  secondaryRole: PlayerResponseDtoSecondaryRole;
  /** Player unique identifier from Riot API */
  puuid: PlayerResponseDtoPuuid;
  /** Profile icon ID of the player */
  profileIconId: PlayerResponseDtoProfileIconId;
  /** Summoner level of the player */
  summonerLevel: PlayerResponseDtoSummonerLevel;
}
