/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Riot Games Player GameName
 */
export type PlayerResponseDtoGameName = { [key: string]: unknown };
