/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { TeamPostingCreateDtoRolesNeededItem } from './teamPostingCreateDtoRolesNeededItem';

export interface TeamPostingCreateDto {
  /** ID of the team creating the posting */
  teamId: number;
  /** Title of the team posting */
  title: string;
  /** Roles needed for the team */
  rolesNeeded: TeamPostingCreateDtoRolesNeededItem[];
  /** Detailed description of the posting */
  description?: string;
}
