/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Status of the invitation
 */
export type TeamInvitationResponseDtoStatus = typeof TeamInvitationResponseDtoStatus[keyof typeof TeamInvitationResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TeamInvitationResponseDtoStatus = {
  REQUESTED: 'REQUESTED',
  PENDING: 'PENDING',
} as const;
