/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

export interface TeamUpdateDto {
  /** Name of the team */
  name: string;
  /** Tag of the team (max 5 characters) */
  tag: string;
  /** description displayed on the team detail page */
  description: string;
  /** Owner user ID */
  ownerId?: number;
}
