/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

/**
 * Current status of the posting
 */
export type TeamPostingResponseDtoStatus = typeof TeamPostingResponseDtoStatus[keyof typeof TeamPostingResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TeamPostingResponseDtoStatus = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
} as const;
