/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { TeamControllerTeamsSortOrder } from './teamControllerTeamsSortOrder';

export type TeamControllerTeamsParams = {
/**
 * Page number (starts from 1)
 */
page?: number;
/**
 * Number of items per page
 */
limit?: number;
/**
 * Offset for pagination
 */
offset?: number;
/**
 * Search term for filtering results
 */
search?: string;
/**
 * Field to sort by
 */
sortBy?: string;
/**
 * Sort order
 */
sortOrder?: TeamControllerTeamsSortOrder;
/**
 * Filter teams by owner user ID
 */
ownerId?: number;
/**
 * Filter teams by member user IDs
 */
members?: number[];
};
