/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

export type TeamPostingCreateDtoRolesNeededItem = typeof TeamPostingCreateDtoRolesNeededItem[keyof typeof TeamPostingCreateDtoRolesNeededItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TeamPostingCreateDtoRolesNeededItem = {
  TOP: 'TOP',
  JUNGLE: 'JUNGLE',
  MID: 'MID',
  CARRY: 'CARRY',
  SUPPORT: 'SUPPORT',
} as const;
