/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { TeamPostingResponseDtoRolesNeededItem } from './teamPostingResponseDtoRolesNeededItem';
import type { TeamPostingResponseDtoStatus } from './teamPostingResponseDtoStatus';
import type { TeamResponseDto } from './teamResponseDto';

export interface TeamPostingResponseDto {
  /** ID of the team creating the posting */
  teamId: number;
  /** Title of the team posting */
  title: string;
  /** Roles needed for the team */
  rolesNeeded: TeamPostingResponseDtoRolesNeededItem[];
  /** Detailed description of the posting */
  description?: string;
  /** Unique identifier for the posting */
  id: number;
  /** Current status of the posting */
  status: TeamPostingResponseDtoStatus;
  /** When the posting was created */
  createdAt: string;
  /** When the posting was last updated */
  updatedAt: string;
  /** The team that created the posting */
  team: TeamResponseDto;
}
