/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { TeamInvitationResponseDtoStatus } from './teamInvitationResponseDtoStatus';
import type { TeamResponseDto } from './teamResponseDto';
import type { PlayerResponseDto } from './playerResponseDto';

export interface TeamInvitationResponseDto {
  /** Invitation ID */
  id: number;
  /** Team ID */
  teamId: number;
  /** Player ID */
  playerId: number;
  /** Creation date of the invitation */
  createdAt: string;
  /** Status of the invitation */
  status: TeamInvitationResponseDtoStatus;
  /** Team object for this invitation */
  team: TeamResponseDto;
  /** Player object for this invitation */
  player: PlayerResponseDto;
}
