/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { TournamentsControllerTournamentsSortOrder } from './tournamentsControllerTournamentsSortOrder';

export type TournamentsControllerTournamentsParams = {
/**
 * Page number (starts from 1)
 */
page?: number;
/**
 * Number of items per page
 */
limit?: number;
/**
 * Field to sort by
 */
sortBy?: string;
/**
 * Sort order
 */
sortOrder?: TournamentsControllerTournamentsSortOrder;
/**
 * Filter by minimum start date
 */
startsAtFrom?: string;
/**
 * Filter by maximum start date
 */
startsAtTo?: string;
/**
 * Filter by team limit
 */
teamLimit?: number;
};
