/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

export interface TournamentUpdateDto {
  /** Tournament name */
  name?: string;
  /** Tournament description */
  description?: string;
  /** The date and time when the tournament starts */
  startsAt?: string;
}
