/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import type { LobbyResponseDto } from './lobbyResponseDto';
import type { TournamentResponseDtoOrganization } from './tournamentResponseDtoOrganization';

export interface TournamentResponseDto {
  /** Tournament ID */
  id: number;
  /** Tournament name */
  name: string;
  /** Tournament description */
  description: string;
  /** Timestamp when tournament was created */
  createdAt: string;
  /** Timestamp when tournament was last updated */
  updatedAt: string;
  /** Timestamp when tournament starts */
  startsAt: string;
  /** ID of the organization hosting the tournament */
  organizationId: number;
  /** Maximum number of teams allowed in the tournament */
  teamLimit: number;
  /** List of lobbies/matches in the tournament */
  lobbies: LobbyResponseDto[];
  /** Organization hosting the tournament */
  organization: TournamentResponseDtoOrganization;
}
