/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */

export type TournamentsControllerTournamentsSortOrder = typeof TournamentsControllerTournamentsSortOrder[keyof typeof TournamentsControllerTournamentsSortOrder];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TournamentsControllerTournamentsSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
