/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  TournamentCreateDto,
  TournamentResponseDto,
  TournamentUpdateDto,
  TournamentsControllerTournamentsParams
} from '.././model';





export const tournamentsControllerTournaments = (
    params?: TournamentsControllerTournamentsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TournamentResponseDto[]>> => {
    
    
    return axios.get(
      `http://localhost:3001/tournaments`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getTournamentsControllerTournamentsQueryKey = (params?: TournamentsControllerTournamentsParams,) => {
    return [`http://localhost:3001/tournaments`, ...(params ? [params]: [])] as const;
    }

    
export const getTournamentsControllerTournamentsQueryOptions = <TData = Awaited<ReturnType<typeof tournamentsControllerTournaments>>, TError = AxiosError<unknown>>(params?: TournamentsControllerTournamentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tournamentsControllerTournaments>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTournamentsControllerTournamentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof tournamentsControllerTournaments>>> = ({ signal }) => tournamentsControllerTournaments(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tournamentsControllerTournaments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TournamentsControllerTournamentsQueryResult = NonNullable<Awaited<ReturnType<typeof tournamentsControllerTournaments>>>
export type TournamentsControllerTournamentsQueryError = AxiosError<unknown>


export function useTournamentsControllerTournaments<TData = Awaited<ReturnType<typeof tournamentsControllerTournaments>>, TError = AxiosError<unknown>>(
 params: undefined |  TournamentsControllerTournamentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tournamentsControllerTournaments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tournamentsControllerTournaments>>,
          TError,
          Awaited<ReturnType<typeof tournamentsControllerTournaments>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTournamentsControllerTournaments<TData = Awaited<ReturnType<typeof tournamentsControllerTournaments>>, TError = AxiosError<unknown>>(
 params?: TournamentsControllerTournamentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tournamentsControllerTournaments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tournamentsControllerTournaments>>,
          TError,
          Awaited<ReturnType<typeof tournamentsControllerTournaments>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTournamentsControllerTournaments<TData = Awaited<ReturnType<typeof tournamentsControllerTournaments>>, TError = AxiosError<unknown>>(
 params?: TournamentsControllerTournamentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tournamentsControllerTournaments>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTournamentsControllerTournaments<TData = Awaited<ReturnType<typeof tournamentsControllerTournaments>>, TError = AxiosError<unknown>>(
 params?: TournamentsControllerTournamentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tournamentsControllerTournaments>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTournamentsControllerTournamentsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const tournamentsControllerCreate = (
    tournamentCreateDto: TournamentCreateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TournamentResponseDto>> => {
    
    
    return axios.post(
      `http://localhost:3001/tournaments`,
      tournamentCreateDto,options
    );
  }



export const getTournamentsControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tournamentsControllerCreate>>, TError,{data: TournamentCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tournamentsControllerCreate>>, TError,{data: TournamentCreateDto}, TContext> => {

const mutationKey = ['tournamentsControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tournamentsControllerCreate>>, {data: TournamentCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  tournamentsControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TournamentsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof tournamentsControllerCreate>>>
    export type TournamentsControllerCreateMutationBody = TournamentCreateDto
    export type TournamentsControllerCreateMutationError = AxiosError<unknown>

    export const useTournamentsControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tournamentsControllerCreate>>, TError,{data: TournamentCreateDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tournamentsControllerCreate>>,
        TError,
        {data: TournamentCreateDto},
        TContext
      > => {

      const mutationOptions = getTournamentsControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const tournamentsControllerTournament = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TournamentResponseDto>> => {
    
    
    return axios.get(
      `http://localhost:3001/tournaments/${id}`,options
    );
  }


export const getTournamentsControllerTournamentQueryKey = (id?: number,) => {
    return [`http://localhost:3001/tournaments/${id}`] as const;
    }

    
export const getTournamentsControllerTournamentQueryOptions = <TData = Awaited<ReturnType<typeof tournamentsControllerTournament>>, TError = AxiosError<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tournamentsControllerTournament>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTournamentsControllerTournamentQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof tournamentsControllerTournament>>> = ({ signal }) => tournamentsControllerTournament(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tournamentsControllerTournament>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TournamentsControllerTournamentQueryResult = NonNullable<Awaited<ReturnType<typeof tournamentsControllerTournament>>>
export type TournamentsControllerTournamentQueryError = AxiosError<unknown>


export function useTournamentsControllerTournament<TData = Awaited<ReturnType<typeof tournamentsControllerTournament>>, TError = AxiosError<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tournamentsControllerTournament>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tournamentsControllerTournament>>,
          TError,
          Awaited<ReturnType<typeof tournamentsControllerTournament>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTournamentsControllerTournament<TData = Awaited<ReturnType<typeof tournamentsControllerTournament>>, TError = AxiosError<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tournamentsControllerTournament>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tournamentsControllerTournament>>,
          TError,
          Awaited<ReturnType<typeof tournamentsControllerTournament>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTournamentsControllerTournament<TData = Awaited<ReturnType<typeof tournamentsControllerTournament>>, TError = AxiosError<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tournamentsControllerTournament>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTournamentsControllerTournament<TData = Awaited<ReturnType<typeof tournamentsControllerTournament>>, TError = AxiosError<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tournamentsControllerTournament>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTournamentsControllerTournamentQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const tournamentsControllerUpdate = (
    id: number,
    tournamentUpdateDto: TournamentUpdateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TournamentResponseDto>> => {
    
    
    return axios.patch(
      `http://localhost:3001/tournaments/${id}`,
      tournamentUpdateDto,options
    );
  }



export const getTournamentsControllerUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tournamentsControllerUpdate>>, TError,{id: number;data: TournamentUpdateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tournamentsControllerUpdate>>, TError,{id: number;data: TournamentUpdateDto}, TContext> => {

const mutationKey = ['tournamentsControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tournamentsControllerUpdate>>, {id: number;data: TournamentUpdateDto}> = (props) => {
          const {id,data} = props ?? {};

          return  tournamentsControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TournamentsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof tournamentsControllerUpdate>>>
    export type TournamentsControllerUpdateMutationBody = TournamentUpdateDto
    export type TournamentsControllerUpdateMutationError = AxiosError<unknown>

    export const useTournamentsControllerUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tournamentsControllerUpdate>>, TError,{id: number;data: TournamentUpdateDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tournamentsControllerUpdate>>,
        TError,
        {id: number;data: TournamentUpdateDto},
        TContext
      > => {

      const mutationOptions = getTournamentsControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const tournamentsControllerJoin = (
    id: number,
    teamId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TournamentResponseDto>> => {
    
    
    return axios.post(
      `http://localhost:3001/tournaments/${id}/join/${teamId}`,undefined,options
    );
  }



export const getTournamentsControllerJoinMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tournamentsControllerJoin>>, TError,{id: number;teamId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tournamentsControllerJoin>>, TError,{id: number;teamId: number}, TContext> => {

const mutationKey = ['tournamentsControllerJoin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tournamentsControllerJoin>>, {id: number;teamId: number}> = (props) => {
          const {id,teamId} = props ?? {};

          return  tournamentsControllerJoin(id,teamId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TournamentsControllerJoinMutationResult = NonNullable<Awaited<ReturnType<typeof tournamentsControllerJoin>>>
    
    export type TournamentsControllerJoinMutationError = AxiosError<unknown>

    export const useTournamentsControllerJoin = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tournamentsControllerJoin>>, TError,{id: number;teamId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tournamentsControllerJoin>>,
        TError,
        {id: number;teamId: number},
        TContext
      > => {

      const mutationOptions = getTournamentsControllerJoinMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const tournamentsControllerLeave = (
    id: number,
    teamId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TournamentResponseDto>> => {
    
    
    return axios.post(
      `http://localhost:3001/tournaments/${id}/leave/${teamId}`,undefined,options
    );
  }



export const getTournamentsControllerLeaveMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tournamentsControllerLeave>>, TError,{id: number;teamId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tournamentsControllerLeave>>, TError,{id: number;teamId: number}, TContext> => {

const mutationKey = ['tournamentsControllerLeave'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tournamentsControllerLeave>>, {id: number;teamId: number}> = (props) => {
          const {id,teamId} = props ?? {};

          return  tournamentsControllerLeave(id,teamId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TournamentsControllerLeaveMutationResult = NonNullable<Awaited<ReturnType<typeof tournamentsControllerLeave>>>
    
    export type TournamentsControllerLeaveMutationError = AxiosError<unknown>

    export const useTournamentsControllerLeave = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tournamentsControllerLeave>>, TError,{id: number;teamId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tournamentsControllerLeave>>,
        TError,
        {id: number;teamId: number},
        TContext
      > => {

      const mutationOptions = getTournamentsControllerLeaveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    