/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  WebhookMatchDTO
} from '.././model';





/**
 * Webhook endpoint called by tracking service when a match starts
 */
export const lobbyWebhookControllerHandleMatchStarted = (
    webhookMatchDTO: WebhookMatchDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<null>> => {
    
    
    return axios.post(
      `http://localhost:3001/webhook/match-started`,
      webhookMatchDTO,options
    );
  }



export const getLobbyWebhookControllerHandleMatchStartedMutationOptions = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyWebhookControllerHandleMatchStarted>>, TError,{data: WebhookMatchDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof lobbyWebhookControllerHandleMatchStarted>>, TError,{data: WebhookMatchDTO}, TContext> => {

const mutationKey = ['lobbyWebhookControllerHandleMatchStarted'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lobbyWebhookControllerHandleMatchStarted>>, {data: WebhookMatchDTO}> = (props) => {
          const {data} = props ?? {};

          return  lobbyWebhookControllerHandleMatchStarted(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LobbyWebhookControllerHandleMatchStartedMutationResult = NonNullable<Awaited<ReturnType<typeof lobbyWebhookControllerHandleMatchStarted>>>
    export type LobbyWebhookControllerHandleMatchStartedMutationBody = WebhookMatchDTO
    export type LobbyWebhookControllerHandleMatchStartedMutationError = AxiosError<null | null>

    export const useLobbyWebhookControllerHandleMatchStarted = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyWebhookControllerHandleMatchStarted>>, TError,{data: WebhookMatchDTO}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lobbyWebhookControllerHandleMatchStarted>>,
        TError,
        {data: WebhookMatchDTO},
        TContext
      > => {

      const mutationOptions = getLobbyWebhookControllerHandleMatchStartedMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Webhook endpoint called by tracking service when a match completes
 */
export const lobbyWebhookControllerHandleMatchCompleted = (
    webhookMatchDTO: WebhookMatchDTO, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<null>> => {
    
    
    return axios.post(
      `http://localhost:3001/webhook/match-completed`,
      webhookMatchDTO,options
    );
  }



export const getLobbyWebhookControllerHandleMatchCompletedMutationOptions = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyWebhookControllerHandleMatchCompleted>>, TError,{data: WebhookMatchDTO}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof lobbyWebhookControllerHandleMatchCompleted>>, TError,{data: WebhookMatchDTO}, TContext> => {

const mutationKey = ['lobbyWebhookControllerHandleMatchCompleted'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof lobbyWebhookControllerHandleMatchCompleted>>, {data: WebhookMatchDTO}> = (props) => {
          const {data} = props ?? {};

          return  lobbyWebhookControllerHandleMatchCompleted(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LobbyWebhookControllerHandleMatchCompletedMutationResult = NonNullable<Awaited<ReturnType<typeof lobbyWebhookControllerHandleMatchCompleted>>>
    export type LobbyWebhookControllerHandleMatchCompletedMutationBody = WebhookMatchDTO
    export type LobbyWebhookControllerHandleMatchCompletedMutationError = AxiosError<null | null>

    export const useLobbyWebhookControllerHandleMatchCompleted = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof lobbyWebhookControllerHandleMatchCompleted>>, TError,{data: WebhookMatchDTO}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof lobbyWebhookControllerHandleMatchCompleted>>,
        TError,
        {data: WebhookMatchDTO},
        TContext
      > => {

      const mutationOptions = getLobbyWebhookControllerHandleMatchCompletedMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    