/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  PlayerPostingControllerPostingsParams,
  PlayerPostingCreateDto,
  PlayerPostingResponseDto,
  TeamPostingControllerPostingsParams,
  TeamPostingCreateDto,
  TeamPostingResponseDto
} from '.././model';





export const teamPostingControllerPostings = (
    params?: TeamPostingControllerPostingsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamPostingResponseDto[]>> => {
    
    
    return axios.get(
      `http://localhost:3001/posting/team`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getTeamPostingControllerPostingsQueryKey = (params?: TeamPostingControllerPostingsParams,) => {
    return [`http://localhost:3001/posting/team`, ...(params ? [params]: [])] as const;
    }

    
export const getTeamPostingControllerPostingsQueryOptions = <TData = Awaited<ReturnType<typeof teamPostingControllerPostings>>, TError = AxiosError<unknown>>(params?: TeamPostingControllerPostingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamPostingControllerPostings>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTeamPostingControllerPostingsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof teamPostingControllerPostings>>> = ({ signal }) => teamPostingControllerPostings(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof teamPostingControllerPostings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TeamPostingControllerPostingsQueryResult = NonNullable<Awaited<ReturnType<typeof teamPostingControllerPostings>>>
export type TeamPostingControllerPostingsQueryError = AxiosError<unknown>


export function useTeamPostingControllerPostings<TData = Awaited<ReturnType<typeof teamPostingControllerPostings>>, TError = AxiosError<unknown>>(
 params: undefined |  TeamPostingControllerPostingsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamPostingControllerPostings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamPostingControllerPostings>>,
          TError,
          Awaited<ReturnType<typeof teamPostingControllerPostings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTeamPostingControllerPostings<TData = Awaited<ReturnType<typeof teamPostingControllerPostings>>, TError = AxiosError<unknown>>(
 params?: TeamPostingControllerPostingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamPostingControllerPostings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamPostingControllerPostings>>,
          TError,
          Awaited<ReturnType<typeof teamPostingControllerPostings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTeamPostingControllerPostings<TData = Awaited<ReturnType<typeof teamPostingControllerPostings>>, TError = AxiosError<unknown>>(
 params?: TeamPostingControllerPostingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamPostingControllerPostings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTeamPostingControllerPostings<TData = Awaited<ReturnType<typeof teamPostingControllerPostings>>, TError = AxiosError<unknown>>(
 params?: TeamPostingControllerPostingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamPostingControllerPostings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTeamPostingControllerPostingsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const teamPostingControllerCreate = (
    teamPostingCreateDto: TeamPostingCreateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamPostingResponseDto>> => {
    
    
    return axios.post(
      `http://localhost:3001/posting/team`,
      teamPostingCreateDto,options
    );
  }



export const getTeamPostingControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamPostingControllerCreate>>, TError,{data: TeamPostingCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof teamPostingControllerCreate>>, TError,{data: TeamPostingCreateDto}, TContext> => {

const mutationKey = ['teamPostingControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof teamPostingControllerCreate>>, {data: TeamPostingCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  teamPostingControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TeamPostingControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof teamPostingControllerCreate>>>
    export type TeamPostingControllerCreateMutationBody = TeamPostingCreateDto
    export type TeamPostingControllerCreateMutationError = AxiosError<unknown>

    export const useTeamPostingControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamPostingControllerCreate>>, TError,{data: TeamPostingCreateDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof teamPostingControllerCreate>>,
        TError,
        {data: TeamPostingCreateDto},
        TContext
      > => {

      const mutationOptions = getTeamPostingControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const teamPostingControllerUpdate = (
    id: number,
    teamPostingCreateDto: TeamPostingCreateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamPostingResponseDto>> => {
    
    
    return axios.patch(
      `http://localhost:3001/posting/team/${id}`,
      teamPostingCreateDto,options
    );
  }



export const getTeamPostingControllerUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamPostingControllerUpdate>>, TError,{id: number;data: TeamPostingCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof teamPostingControllerUpdate>>, TError,{id: number;data: TeamPostingCreateDto}, TContext> => {

const mutationKey = ['teamPostingControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof teamPostingControllerUpdate>>, {id: number;data: TeamPostingCreateDto}> = (props) => {
          const {id,data} = props ?? {};

          return  teamPostingControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TeamPostingControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof teamPostingControllerUpdate>>>
    export type TeamPostingControllerUpdateMutationBody = TeamPostingCreateDto
    export type TeamPostingControllerUpdateMutationError = AxiosError<unknown>

    export const useTeamPostingControllerUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamPostingControllerUpdate>>, TError,{id: number;data: TeamPostingCreateDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof teamPostingControllerUpdate>>,
        TError,
        {id: number;data: TeamPostingCreateDto},
        TContext
      > => {

      const mutationOptions = getTeamPostingControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const teamPostingControllerDelete = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamPostingResponseDto>> => {
    
    
    return axios.delete(
      `http://localhost:3001/posting/team/${id}`,options
    );
  }



export const getTeamPostingControllerDeleteMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamPostingControllerDelete>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof teamPostingControllerDelete>>, TError,{id: number}, TContext> => {

const mutationKey = ['teamPostingControllerDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof teamPostingControllerDelete>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  teamPostingControllerDelete(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TeamPostingControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof teamPostingControllerDelete>>>
    
    export type TeamPostingControllerDeleteMutationError = AxiosError<unknown>

    export const useTeamPostingControllerDelete = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamPostingControllerDelete>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof teamPostingControllerDelete>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getTeamPostingControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const playerPostingControllerPostings = (
    params?: PlayerPostingControllerPostingsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerPostingResponseDto[]>> => {
    
    
    return axios.get(
      `http://localhost:3001/posting/player`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getPlayerPostingControllerPostingsQueryKey = (params?: PlayerPostingControllerPostingsParams,) => {
    return [`http://localhost:3001/posting/player`, ...(params ? [params]: [])] as const;
    }

    
export const getPlayerPostingControllerPostingsQueryOptions = <TData = Awaited<ReturnType<typeof playerPostingControllerPostings>>, TError = AxiosError<unknown>>(params?: PlayerPostingControllerPostingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playerPostingControllerPostings>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlayerPostingControllerPostingsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof playerPostingControllerPostings>>> = ({ signal }) => playerPostingControllerPostings(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof playerPostingControllerPostings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PlayerPostingControllerPostingsQueryResult = NonNullable<Awaited<ReturnType<typeof playerPostingControllerPostings>>>
export type PlayerPostingControllerPostingsQueryError = AxiosError<unknown>


export function usePlayerPostingControllerPostings<TData = Awaited<ReturnType<typeof playerPostingControllerPostings>>, TError = AxiosError<unknown>>(
 params: undefined |  PlayerPostingControllerPostingsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof playerPostingControllerPostings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof playerPostingControllerPostings>>,
          TError,
          Awaited<ReturnType<typeof playerPostingControllerPostings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlayerPostingControllerPostings<TData = Awaited<ReturnType<typeof playerPostingControllerPostings>>, TError = AxiosError<unknown>>(
 params?: PlayerPostingControllerPostingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playerPostingControllerPostings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof playerPostingControllerPostings>>,
          TError,
          Awaited<ReturnType<typeof playerPostingControllerPostings>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlayerPostingControllerPostings<TData = Awaited<ReturnType<typeof playerPostingControllerPostings>>, TError = AxiosError<unknown>>(
 params?: PlayerPostingControllerPostingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playerPostingControllerPostings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePlayerPostingControllerPostings<TData = Awaited<ReturnType<typeof playerPostingControllerPostings>>, TError = AxiosError<unknown>>(
 params?: PlayerPostingControllerPostingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playerPostingControllerPostings>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPlayerPostingControllerPostingsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const playerPostingControllerCreate = (
    playerPostingCreateDto: PlayerPostingCreateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerPostingResponseDto>> => {
    
    
    return axios.post(
      `http://localhost:3001/posting/player`,
      playerPostingCreateDto,options
    );
  }



export const getPlayerPostingControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof playerPostingControllerCreate>>, TError,{data: PlayerPostingCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof playerPostingControllerCreate>>, TError,{data: PlayerPostingCreateDto}, TContext> => {

const mutationKey = ['playerPostingControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof playerPostingControllerCreate>>, {data: PlayerPostingCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  playerPostingControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PlayerPostingControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof playerPostingControllerCreate>>>
    export type PlayerPostingControllerCreateMutationBody = PlayerPostingCreateDto
    export type PlayerPostingControllerCreateMutationError = AxiosError<unknown>

    export const usePlayerPostingControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof playerPostingControllerCreate>>, TError,{data: PlayerPostingCreateDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof playerPostingControllerCreate>>,
        TError,
        {data: PlayerPostingCreateDto},
        TContext
      > => {

      const mutationOptions = getPlayerPostingControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const playerPostingControllerUpdate = (
    id: number,
    playerPostingCreateDto: PlayerPostingCreateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerPostingResponseDto>> => {
    
    
    return axios.patch(
      `http://localhost:3001/posting/player/${id}`,
      playerPostingCreateDto,options
    );
  }



export const getPlayerPostingControllerUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof playerPostingControllerUpdate>>, TError,{id: number;data: PlayerPostingCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof playerPostingControllerUpdate>>, TError,{id: number;data: PlayerPostingCreateDto}, TContext> => {

const mutationKey = ['playerPostingControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof playerPostingControllerUpdate>>, {id: number;data: PlayerPostingCreateDto}> = (props) => {
          const {id,data} = props ?? {};

          return  playerPostingControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PlayerPostingControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof playerPostingControllerUpdate>>>
    export type PlayerPostingControllerUpdateMutationBody = PlayerPostingCreateDto
    export type PlayerPostingControllerUpdateMutationError = AxiosError<unknown>

    export const usePlayerPostingControllerUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof playerPostingControllerUpdate>>, TError,{id: number;data: PlayerPostingCreateDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof playerPostingControllerUpdate>>,
        TError,
        {id: number;data: PlayerPostingCreateDto},
        TContext
      > => {

      const mutationOptions = getPlayerPostingControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const playerPostingControllerDelete = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerPostingResponseDto>> => {
    
    
    return axios.delete(
      `http://localhost:3001/posting/player/${id}`,options
    );
  }



export const getPlayerPostingControllerDeleteMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof playerPostingControllerDelete>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof playerPostingControllerDelete>>, TError,{id: number}, TContext> => {

const mutationKey = ['playerPostingControllerDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof playerPostingControllerDelete>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  playerPostingControllerDelete(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PlayerPostingControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof playerPostingControllerDelete>>>
    
    export type PlayerPostingControllerDeleteMutationError = AxiosError<unknown>

    export const usePlayerPostingControllerDelete = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof playerPostingControllerDelete>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof playerPostingControllerDelete>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getPlayerPostingControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    