/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  TeamInvitationResponseDto,
  TeamResponseDto
} from '.././model';





export const teamInvitationsControllerGetTeamInvitations = (
    teamId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamInvitationResponseDto[]>> => {
    
    
    return axios.get(
      `http://localhost:3001/teams/${teamId}/invitations`,options
    );
  }


export const getTeamInvitationsControllerGetTeamInvitationsQueryKey = (teamId?: number,) => {
    return [`http://localhost:3001/teams/${teamId}/invitations`] as const;
    }

    
export const getTeamInvitationsControllerGetTeamInvitationsQueryOptions = <TData = Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>, TError = AxiosError<unknown>>(teamId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTeamInvitationsControllerGetTeamInvitationsQueryKey(teamId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>> = ({ signal }) => teamInvitationsControllerGetTeamInvitations(teamId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(teamId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TeamInvitationsControllerGetTeamInvitationsQueryResult = NonNullable<Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>>
export type TeamInvitationsControllerGetTeamInvitationsQueryError = AxiosError<unknown>


export function useTeamInvitationsControllerGetTeamInvitations<TData = Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>, TError = AxiosError<unknown>>(
 teamId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>,
          TError,
          Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTeamInvitationsControllerGetTeamInvitations<TData = Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>, TError = AxiosError<unknown>>(
 teamId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>,
          TError,
          Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTeamInvitationsControllerGetTeamInvitations<TData = Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>, TError = AxiosError<unknown>>(
 teamId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTeamInvitationsControllerGetTeamInvitations<TData = Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>, TError = AxiosError<unknown>>(
 teamId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamInvitationsControllerGetTeamInvitations>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTeamInvitationsControllerGetTeamInvitationsQueryOptions(teamId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const teamInvitationsControllerCreateInvitation = (
    teamId: number,
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamInvitationResponseDto>> => {
    
    
    return axios.post(
      `http://localhost:3001/teams/${teamId}/invitations/${id}`,undefined,options
    );
  }



export const getTeamInvitationsControllerCreateInvitationMutationOptions = <TError = AxiosError<null | null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamInvitationsControllerCreateInvitation>>, TError,{teamId: number;id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof teamInvitationsControllerCreateInvitation>>, TError,{teamId: number;id: number}, TContext> => {

const mutationKey = ['teamInvitationsControllerCreateInvitation'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof teamInvitationsControllerCreateInvitation>>, {teamId: number;id: number}> = (props) => {
          const {teamId,id} = props ?? {};

          return  teamInvitationsControllerCreateInvitation(teamId,id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TeamInvitationsControllerCreateInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof teamInvitationsControllerCreateInvitation>>>
    
    export type TeamInvitationsControllerCreateInvitationMutationError = AxiosError<null | null | null>

    export const useTeamInvitationsControllerCreateInvitation = <TError = AxiosError<null | null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamInvitationsControllerCreateInvitation>>, TError,{teamId: number;id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof teamInvitationsControllerCreateInvitation>>,
        TError,
        {teamId: number;id: number},
        TContext
      > => {

      const mutationOptions = getTeamInvitationsControllerCreateInvitationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const teamInvitationsControllerUpdateInvitation = (
    teamId: number,
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamInvitationResponseDto>> => {
    
    
    return axios.patch(
      `http://localhost:3001/teams/${teamId}/invitations/${id}`,undefined,options
    );
  }



export const getTeamInvitationsControllerUpdateInvitationMutationOptions = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamInvitationsControllerUpdateInvitation>>, TError,{teamId: number;id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof teamInvitationsControllerUpdateInvitation>>, TError,{teamId: number;id: number}, TContext> => {

const mutationKey = ['teamInvitationsControllerUpdateInvitation'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof teamInvitationsControllerUpdateInvitation>>, {teamId: number;id: number}> = (props) => {
          const {teamId,id} = props ?? {};

          return  teamInvitationsControllerUpdateInvitation(teamId,id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TeamInvitationsControllerUpdateInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof teamInvitationsControllerUpdateInvitation>>>
    
    export type TeamInvitationsControllerUpdateInvitationMutationError = AxiosError<null | null>

    export const useTeamInvitationsControllerUpdateInvitation = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamInvitationsControllerUpdateInvitation>>, TError,{teamId: number;id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof teamInvitationsControllerUpdateInvitation>>,
        TError,
        {teamId: number;id: number},
        TContext
      > => {

      const mutationOptions = getTeamInvitationsControllerUpdateInvitationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const teamInvitationsControllerRequestInvitation = (
    teamId: number,
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamInvitationResponseDto>> => {
    
    
    return axios.put(
      `http://localhost:3001/teams/${teamId}/invitations/${id}`,undefined,options
    );
  }



export const getTeamInvitationsControllerRequestInvitationMutationOptions = <TError = AxiosError<null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamInvitationsControllerRequestInvitation>>, TError,{teamId: number;id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof teamInvitationsControllerRequestInvitation>>, TError,{teamId: number;id: number}, TContext> => {

const mutationKey = ['teamInvitationsControllerRequestInvitation'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof teamInvitationsControllerRequestInvitation>>, {teamId: number;id: number}> = (props) => {
          const {teamId,id} = props ?? {};

          return  teamInvitationsControllerRequestInvitation(teamId,id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TeamInvitationsControllerRequestInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof teamInvitationsControllerRequestInvitation>>>
    
    export type TeamInvitationsControllerRequestInvitationMutationError = AxiosError<null>

    export const useTeamInvitationsControllerRequestInvitation = <TError = AxiosError<null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamInvitationsControllerRequestInvitation>>, TError,{teamId: number;id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof teamInvitationsControllerRequestInvitation>>,
        TError,
        {teamId: number;id: number},
        TContext
      > => {

      const mutationOptions = getTeamInvitationsControllerRequestInvitationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const teamInvitationsControllerGetInvitations = (
    teamId: number,
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamInvitationResponseDto[]>> => {
    
    
    return axios.get(
      `http://localhost:3001/teams/${teamId}/invitations/${id}`,options
    );
  }


export const getTeamInvitationsControllerGetInvitationsQueryKey = (teamId?: number,
    id?: number,) => {
    return [`http://localhost:3001/teams/${teamId}/invitations/${id}`] as const;
    }

    
export const getTeamInvitationsControllerGetInvitationsQueryOptions = <TData = Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>, TError = AxiosError<unknown>>(teamId: number,
    id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTeamInvitationsControllerGetInvitationsQueryKey(teamId,id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>> = ({ signal }) => teamInvitationsControllerGetInvitations(teamId,id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(teamId && id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TeamInvitationsControllerGetInvitationsQueryResult = NonNullable<Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>>
export type TeamInvitationsControllerGetInvitationsQueryError = AxiosError<unknown>


export function useTeamInvitationsControllerGetInvitations<TData = Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>, TError = AxiosError<unknown>>(
 teamId: number,
    id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>,
          TError,
          Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTeamInvitationsControllerGetInvitations<TData = Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>, TError = AxiosError<unknown>>(
 teamId: number,
    id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>,
          TError,
          Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTeamInvitationsControllerGetInvitations<TData = Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>, TError = AxiosError<unknown>>(
 teamId: number,
    id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTeamInvitationsControllerGetInvitations<TData = Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>, TError = AxiosError<unknown>>(
 teamId: number,
    id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamInvitationsControllerGetInvitations>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTeamInvitationsControllerGetInvitationsQueryOptions(teamId,id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const teamInvitationsControllerRemoveMember = (
    teamId: number,
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamResponseDto>> => {
    
    
    return axios.delete(
      `http://localhost:3001/teams/${teamId}/invitations/${id}`,options
    );
  }



export const getTeamInvitationsControllerRemoveMemberMutationOptions = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamInvitationsControllerRemoveMember>>, TError,{teamId: number;id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof teamInvitationsControllerRemoveMember>>, TError,{teamId: number;id: number}, TContext> => {

const mutationKey = ['teamInvitationsControllerRemoveMember'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof teamInvitationsControllerRemoveMember>>, {teamId: number;id: number}> = (props) => {
          const {teamId,id} = props ?? {};

          return  teamInvitationsControllerRemoveMember(teamId,id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TeamInvitationsControllerRemoveMemberMutationResult = NonNullable<Awaited<ReturnType<typeof teamInvitationsControllerRemoveMember>>>
    
    export type TeamInvitationsControllerRemoveMemberMutationError = AxiosError<null | null>

    export const useTeamInvitationsControllerRemoveMember = <TError = AxiosError<null | null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamInvitationsControllerRemoveMember>>, TError,{teamId: number;id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof teamInvitationsControllerRemoveMember>>,
        TError,
        {teamId: number;id: number},
        TContext
      > => {

      const mutationOptions = getTeamInvitationsControllerRemoveMemberMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    