/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  TeamControllerTeamsParams,
  TeamCreateDto,
  TeamResponseDto,
  TeamUpdateDto
} from '.././model';





export const teamControllerTeams = (
    params?: TeamControllerTeamsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamResponseDto[]>> => {
    
    
    return axios.get(
      `http://localhost:3001/teams`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getTeamControllerTeamsQueryKey = (params?: TeamControllerTeamsParams,) => {
    return [`http://localhost:3001/teams`, ...(params ? [params]: [])] as const;
    }

    
export const getTeamControllerTeamsQueryOptions = <TData = Awaited<ReturnType<typeof teamControllerTeams>>, TError = AxiosError<unknown>>(params?: TeamControllerTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamControllerTeams>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTeamControllerTeamsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof teamControllerTeams>>> = ({ signal }) => teamControllerTeams(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof teamControllerTeams>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TeamControllerTeamsQueryResult = NonNullable<Awaited<ReturnType<typeof teamControllerTeams>>>
export type TeamControllerTeamsQueryError = AxiosError<unknown>


export function useTeamControllerTeams<TData = Awaited<ReturnType<typeof teamControllerTeams>>, TError = AxiosError<unknown>>(
 params: undefined |  TeamControllerTeamsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamControllerTeams>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamControllerTeams>>,
          TError,
          Awaited<ReturnType<typeof teamControllerTeams>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTeamControllerTeams<TData = Awaited<ReturnType<typeof teamControllerTeams>>, TError = AxiosError<unknown>>(
 params?: TeamControllerTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamControllerTeams>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamControllerTeams>>,
          TError,
          Awaited<ReturnType<typeof teamControllerTeams>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTeamControllerTeams<TData = Awaited<ReturnType<typeof teamControllerTeams>>, TError = AxiosError<unknown>>(
 params?: TeamControllerTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamControllerTeams>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTeamControllerTeams<TData = Awaited<ReturnType<typeof teamControllerTeams>>, TError = AxiosError<unknown>>(
 params?: TeamControllerTeamsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamControllerTeams>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTeamControllerTeamsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const teamControllerCreate = (
    teamCreateDto: TeamCreateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamResponseDto>> => {
    
    
    return axios.post(
      `http://localhost:3001/teams`,
      teamCreateDto,options
    );
  }



export const getTeamControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamControllerCreate>>, TError,{data: TeamCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof teamControllerCreate>>, TError,{data: TeamCreateDto}, TContext> => {

const mutationKey = ['teamControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof teamControllerCreate>>, {data: TeamCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  teamControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TeamControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof teamControllerCreate>>>
    export type TeamControllerCreateMutationBody = TeamCreateDto
    export type TeamControllerCreateMutationError = AxiosError<unknown>

    export const useTeamControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamControllerCreate>>, TError,{data: TeamCreateDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof teamControllerCreate>>,
        TError,
        {data: TeamCreateDto},
        TContext
      > => {

      const mutationOptions = getTeamControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const teamControllerTeam = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamResponseDto>> => {
    
    
    return axios.get(
      `http://localhost:3001/teams/${id}`,options
    );
  }


export const getTeamControllerTeamQueryKey = (id?: number,) => {
    return [`http://localhost:3001/teams/${id}`] as const;
    }

    
export const getTeamControllerTeamQueryOptions = <TData = Awaited<ReturnType<typeof teamControllerTeam>>, TError = AxiosError<unknown>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamControllerTeam>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTeamControllerTeamQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof teamControllerTeam>>> = ({ signal }) => teamControllerTeam(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof teamControllerTeam>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TeamControllerTeamQueryResult = NonNullable<Awaited<ReturnType<typeof teamControllerTeam>>>
export type TeamControllerTeamQueryError = AxiosError<unknown>


export function useTeamControllerTeam<TData = Awaited<ReturnType<typeof teamControllerTeam>>, TError = AxiosError<unknown>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamControllerTeam>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamControllerTeam>>,
          TError,
          Awaited<ReturnType<typeof teamControllerTeam>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTeamControllerTeam<TData = Awaited<ReturnType<typeof teamControllerTeam>>, TError = AxiosError<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamControllerTeam>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamControllerTeam>>,
          TError,
          Awaited<ReturnType<typeof teamControllerTeam>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTeamControllerTeam<TData = Awaited<ReturnType<typeof teamControllerTeam>>, TError = AxiosError<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamControllerTeam>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTeamControllerTeam<TData = Awaited<ReturnType<typeof teamControllerTeam>>, TError = AxiosError<unknown>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof teamControllerTeam>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTeamControllerTeamQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const teamControllerUpdate = (
    id: number,
    teamUpdateDto: TeamUpdateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamResponseDto>> => {
    
    
    return axios.patch(
      `http://localhost:3001/teams/${id}`,
      teamUpdateDto,options
    );
  }



export const getTeamControllerUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamControllerUpdate>>, TError,{id: number;data: TeamUpdateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof teamControllerUpdate>>, TError,{id: number;data: TeamUpdateDto}, TContext> => {

const mutationKey = ['teamControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof teamControllerUpdate>>, {id: number;data: TeamUpdateDto}> = (props) => {
          const {id,data} = props ?? {};

          return  teamControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TeamControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof teamControllerUpdate>>>
    export type TeamControllerUpdateMutationBody = TeamUpdateDto
    export type TeamControllerUpdateMutationError = AxiosError<unknown>

    export const useTeamControllerUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamControllerUpdate>>, TError,{id: number;data: TeamUpdateDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof teamControllerUpdate>>,
        TError,
        {id: number;data: TeamUpdateDto},
        TContext
      > => {

      const mutationOptions = getTeamControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const teamControllerRemove = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TeamResponseDto>> => {
    
    
    return axios.delete(
      `http://localhost:3001/teams/${id}`,options
    );
  }



export const getTeamControllerRemoveMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamControllerRemove>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof teamControllerRemove>>, TError,{id: number}, TContext> => {

const mutationKey = ['teamControllerRemove'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof teamControllerRemove>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  teamControllerRemove(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TeamControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof teamControllerRemove>>>
    
    export type TeamControllerRemoveMutationError = AxiosError<unknown>

    export const useTeamControllerRemove = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof teamControllerRemove>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof teamControllerRemove>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getTeamControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    