/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  MatchControllerFindMatchParams,
  MatchResponseDto
} from '.././model';





/**
 * Retrieves match details including all participants and stats. Provide either riotMatchId or lobbyId query parameter.
 * @summary Find match by Riot match ID or lobby ID
 */
export const matchControllerFindMatch = (
    params?: MatchControllerFindMatchParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MatchResponseDto>> => {
    
    
    return axios.get(
      `http://localhost:3001/match`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getMatchControllerFindMatchQueryKey = (params?: MatchControllerFindMatchParams,) => {
    return [`http://localhost:3001/match`, ...(params ? [params]: [])] as const;
    }

    
export const getMatchControllerFindMatchQueryOptions = <TData = Awaited<ReturnType<typeof matchControllerFindMatch>>, TError = AxiosError<null | null>>(params?: MatchControllerFindMatchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof matchControllerFindMatch>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMatchControllerFindMatchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof matchControllerFindMatch>>> = ({ signal }) => matchControllerFindMatch(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof matchControllerFindMatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MatchControllerFindMatchQueryResult = NonNullable<Awaited<ReturnType<typeof matchControllerFindMatch>>>
export type MatchControllerFindMatchQueryError = AxiosError<null | null>


export function useMatchControllerFindMatch<TData = Awaited<ReturnType<typeof matchControllerFindMatch>>, TError = AxiosError<null | null>>(
 params: undefined |  MatchControllerFindMatchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof matchControllerFindMatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof matchControllerFindMatch>>,
          TError,
          Awaited<ReturnType<typeof matchControllerFindMatch>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMatchControllerFindMatch<TData = Awaited<ReturnType<typeof matchControllerFindMatch>>, TError = AxiosError<null | null>>(
 params?: MatchControllerFindMatchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof matchControllerFindMatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof matchControllerFindMatch>>,
          TError,
          Awaited<ReturnType<typeof matchControllerFindMatch>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMatchControllerFindMatch<TData = Awaited<ReturnType<typeof matchControllerFindMatch>>, TError = AxiosError<null | null>>(
 params?: MatchControllerFindMatchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof matchControllerFindMatch>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Find match by Riot match ID or lobby ID
 */

export function useMatchControllerFindMatch<TData = Awaited<ReturnType<typeof matchControllerFindMatch>>, TError = AxiosError<null | null>>(
 params?: MatchControllerFindMatchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof matchControllerFindMatch>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMatchControllerFindMatchQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



