/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  OrganizationCreateDto,
  OrganizationResponseDto,
  OrganizationUpdateDto
} from '.././model';





export const organizationsControllerGetMyOrganization = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationResponseDto>> => {
    
    
    return axios.get(
      `http://localhost:3001/organizations`,options
    );
  }


export const getOrganizationsControllerGetMyOrganizationQueryKey = () => {
    return [`http://localhost:3001/organizations`] as const;
    }

    
export const getOrganizationsControllerGetMyOrganizationQueryOptions = <TData = Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationsControllerGetMyOrganizationQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>> = ({ signal }) => organizationsControllerGetMyOrganization({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationsControllerGetMyOrganizationQueryResult = NonNullable<Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>>
export type OrganizationsControllerGetMyOrganizationQueryError = AxiosError<unknown>


export function useOrganizationsControllerGetMyOrganization<TData = Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsControllerGetMyOrganization<TData = Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsControllerGetMyOrganization<TData = Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useOrganizationsControllerGetMyOrganization<TData = Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetMyOrganization>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationsControllerGetMyOrganizationQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const organizationsControllerCreate = (
    organizationCreateDto: OrganizationCreateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationResponseDto>> => {
    
    
    return axios.post(
      `http://localhost:3001/organizations`,
      organizationCreateDto,options
    );
  }



export const getOrganizationsControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerCreate>>, TError,{data: OrganizationCreateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerCreate>>, TError,{data: OrganizationCreateDto}, TContext> => {

const mutationKey = ['organizationsControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsControllerCreate>>, {data: OrganizationCreateDto}> = (props) => {
          const {data} = props ?? {};

          return  organizationsControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsControllerCreate>>>
    export type OrganizationsControllerCreateMutationBody = OrganizationCreateDto
    export type OrganizationsControllerCreateMutationError = AxiosError<unknown>

    export const useOrganizationsControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerCreate>>, TError,{data: OrganizationCreateDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsControllerCreate>>,
        TError,
        {data: OrganizationCreateDto},
        TContext
      > => {

      const mutationOptions = getOrganizationsControllerCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const organizationsControllerUpdate = (
    id: number,
    organizationUpdateDto: OrganizationUpdateDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationResponseDto>> => {
    
    
    return axios.patch(
      `http://localhost:3001/organizations/${id}`,
      organizationUpdateDto,options
    );
  }



export const getOrganizationsControllerUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerUpdate>>, TError,{id: number;data: OrganizationUpdateDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerUpdate>>, TError,{id: number;data: OrganizationUpdateDto}, TContext> => {

const mutationKey = ['organizationsControllerUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsControllerUpdate>>, {id: number;data: OrganizationUpdateDto}> = (props) => {
          const {id,data} = props ?? {};

          return  organizationsControllerUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsControllerUpdate>>>
    export type OrganizationsControllerUpdateMutationBody = OrganizationUpdateDto
    export type OrganizationsControllerUpdateMutationError = AxiosError<unknown>

    export const useOrganizationsControllerUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerUpdate>>, TError,{id: number;data: OrganizationUpdateDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsControllerUpdate>>,
        TError,
        {id: number;data: OrganizationUpdateDto},
        TContext
      > => {

      const mutationOptions = getOrganizationsControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const organizationsControllerDelete = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationResponseDto>> => {
    
    
    return axios.delete(
      `http://localhost:3001/organizations/${id}`,options
    );
  }



export const getOrganizationsControllerDeleteMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerDelete>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerDelete>>, TError,{id: number}, TContext> => {

const mutationKey = ['organizationsControllerDelete'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsControllerDelete>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  organizationsControllerDelete(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsControllerDelete>>>
    
    export type OrganizationsControllerDeleteMutationError = AxiosError<unknown>

    export const useOrganizationsControllerDelete = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerDelete>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsControllerDelete>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getOrganizationsControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    