/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreatePlayerDto,
  PlayerControllerPlayersParams,
  PlayerResponseDto
} from '.././model';





export const playerControllerPlayers = (
    params?: PlayerControllerPlayersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerResponseDto[]>> => {
    
    
    return axios.get(
      `http://localhost:3001/player`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getPlayerControllerPlayersQueryKey = (params?: PlayerControllerPlayersParams,) => {
    return [`http://localhost:3001/player`, ...(params ? [params]: [])] as const;
    }

    
export const getPlayerControllerPlayersQueryOptions = <TData = Awaited<ReturnType<typeof playerControllerPlayers>>, TError = AxiosError<unknown>>(params?: PlayerControllerPlayersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerPlayers>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlayerControllerPlayersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof playerControllerPlayers>>> = ({ signal }) => playerControllerPlayers(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof playerControllerPlayers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PlayerControllerPlayersQueryResult = NonNullable<Awaited<ReturnType<typeof playerControllerPlayers>>>
export type PlayerControllerPlayersQueryError = AxiosError<unknown>


export function usePlayerControllerPlayers<TData = Awaited<ReturnType<typeof playerControllerPlayers>>, TError = AxiosError<unknown>>(
 params: undefined |  PlayerControllerPlayersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerPlayers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof playerControllerPlayers>>,
          TError,
          Awaited<ReturnType<typeof playerControllerPlayers>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlayerControllerPlayers<TData = Awaited<ReturnType<typeof playerControllerPlayers>>, TError = AxiosError<unknown>>(
 params?: PlayerControllerPlayersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerPlayers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof playerControllerPlayers>>,
          TError,
          Awaited<ReturnType<typeof playerControllerPlayers>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlayerControllerPlayers<TData = Awaited<ReturnType<typeof playerControllerPlayers>>, TError = AxiosError<unknown>>(
 params?: PlayerControllerPlayersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerPlayers>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePlayerControllerPlayers<TData = Awaited<ReturnType<typeof playerControllerPlayers>>, TError = AxiosError<unknown>>(
 params?: PlayerControllerPlayersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof playerControllerPlayers>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPlayerControllerPlayersQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const playerControllerUpsert = (
    createPlayerDto: CreatePlayerDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerResponseDto>> => {
    
    
    return axios.put(
      `http://localhost:3001/player`,
      createPlayerDto,options
    );
  }



export const getPlayerControllerUpsertMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof playerControllerUpsert>>, TError,{data: CreatePlayerDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof playerControllerUpsert>>, TError,{data: CreatePlayerDto}, TContext> => {

const mutationKey = ['playerControllerUpsert'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof playerControllerUpsert>>, {data: CreatePlayerDto}> = (props) => {
          const {data} = props ?? {};

          return  playerControllerUpsert(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PlayerControllerUpsertMutationResult = NonNullable<Awaited<ReturnType<typeof playerControllerUpsert>>>
    export type PlayerControllerUpsertMutationBody = CreatePlayerDto
    export type PlayerControllerUpsertMutationError = AxiosError<unknown>

    export const usePlayerControllerUpsert = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof playerControllerUpsert>>, TError,{data: CreatePlayerDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof playerControllerUpsert>>,
        TError,
        {data: CreatePlayerDto},
        TContext
      > => {

      const mutationOptions = getPlayerControllerUpsertMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    