/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Student Arena API
 * API Documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreatePlayerDto,
  PlayerResponseDto
} from '.././model';





export const playerControllerUpsert = (
    createPlayerDto: CreatePlayerDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PlayerResponseDto>> => {
    
    
    return axios.put(
      `http://localhost:3001/player`,
      createPlayerDto,options
    );
  }



export const getPlayerControllerUpsertMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof playerControllerUpsert>>, TError,{data: CreatePlayerDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof playerControllerUpsert>>, TError,{data: CreatePlayerDto}, TContext> => {

const mutationKey = ['playerControllerUpsert'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof playerControllerUpsert>>, {data: CreatePlayerDto}> = (props) => {
          const {data} = props ?? {};

          return  playerControllerUpsert(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PlayerControllerUpsertMutationResult = NonNullable<Awaited<ReturnType<typeof playerControllerUpsert>>>
    export type PlayerControllerUpsertMutationBody = CreatePlayerDto
    export type PlayerControllerUpsertMutationError = AxiosError<unknown>

    export const usePlayerControllerUpsert = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof playerControllerUpsert>>, TError,{data: CreatePlayerDto}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof playerControllerUpsert>>,
        TError,
        {data: CreatePlayerDto},
        TContext
      > => {

      const mutationOptions = getPlayerControllerUpsertMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    