name: Backend CI

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: backend/package.json

      - name: Install dependencies
        run: npm ci

      - name: Generate prisma types
        run: npx prisma generate

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build
